[package]
name = "client"
version = "0.1.0"
authors = ["Cyril Mizzi <cyril@lesiteimmo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11 = { path = "../x11" }